#!/bin/bash
# fileCreate measures the time it takes to create a 64kB file.
# Create is defined at: open file, write to file, close file.  
# Each indivdual file time is written to Avgtimes.txt in form: 
# Start time, finish time
# Overall time is printed at the end

# Deletes the old Values
rm !!<Working Dir>!!/Avgtimes.txt
touch !!<Working Dir>!!/Avgtimes.txt


rm !!<Target Dir>!!/Meta/testfiles 
mkdir -p !!<Target Dir>!!/Meta/testfiles

# Records start of file Creation
total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

# Number of files 
for i in {1..!!<Number Files>!!};
do

echo $(($(date +'%s * 1000 + %-N')/ 1000000)) >> Avgtimes.txt

# Creates 1 file size !!<Size>!!
dd < /dev/zero bs=!!<Size>!! count=1 > !!<Target Dir>!!/testfiles/testfile$i


echo $(($(date +'%s * 1000 + %-N')/ 1000000)) >> Avgtimes.txt


done

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

echo " "
echo " "
echo "total time: "

echo "$(($total2-$total1)) milliseconds"



