#!/bin/bash

rm Avgtimes.txt
touch Avgtimes.txt

rm -rf /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/testfiles 
mkdir /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/testfiles

total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

for i in {1..100};
do

echo $(($(date +'%s * 1000 + %-N')/ 1000000)) >> Avgtimes.txt

dd < /dev/zero bs=64000 count=1 > /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/testfiles/testfile$i
echo $(($(date +'%s * 1000 + %-N')/ 1000000)) >> Avgtimes.txt


done

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

echo " "
echo " "
echo "total time: "

echo "$(($total2-$total1)) milliseconds"



