#!/bin/bash
# Master shell script for vidio

# Removes any old file for Depthteseter script, then creates a new one
rm DepthTest.txt
touch DepthTest.txt

for i in {0..15}; do sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/; done

# Runs the Depth tester script that outputs to test.txt
sudo .!!<Working Dir>!!/scripts/VIDIODEPTHTESTER

# Removes old best.txt and creates new empty one
sudo rm !!<Working Dir>!!/resources/BestDepth.txt
sudo touch !!<Working Dir>!!/resources/BestDepth.txt

# runs python parser to get best Depth tester
sudo python !!<Working Dir>!!/scripts/BestQueueDepth.py !!<Working Dir>!!/resources/DepthTest.txt !!<Working Dir>!!/resources/BestDepth.txt

# Add to history to see what its like from this point on I
sudo !!<Working Dir>!!/resources/BestDepth.txt >> !!<Working Dir>!!/resources/history/bestHistory.txt

#Runs script with best.txt result as macro
sudo .!!<Working Dir>!!/scripts/VIDIOBASH

# makes a new file for final results of big test
sudo cp !!<Working Dir>!!/results/vidioResults.txt !!<Working Dir>!!/results/backupResults.txt
sudo rm !!<Working Dir>!!/results/vidioResults.txt
sudo touch !!<Working Dir>!!/results/vidioResults.txt
sudo cp !!<Working Dir>!!/results/vidioMetaResults.txt !!<Working Dir>!!/results/backupMetaResults.txt
sudo rm !!<Working Dir>!!/results/vidioMetaResults.txt
sudo touch !!<Working Dir>!!/results/vidioMetaResults.txt

sudo python !!<Working Dir>!!/scripts/vidioResultsParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioResults.txt
sudo python !!<Working Dir>!!/scripts/vidioMeta Parser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioMetaResults.txt
sudo cat !!<Working Dir>!!/results/vidioResults.txt
sudo cat !!<Working Dir>!!/results/vidioMetaResults.txt

