#!/bin/bash
# Master shell script for vidio

# Removes any old file for Depthteseter script, then creates a new one
rm DepthTest.txt
touch DepthTest.txt

for i in {0..15}; do mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/; done

# Runs the Depth tester script that outputs to test.txt
.!!<Working Dir>!!/scripts/VIDIODEPTHTESTER

# Removes old best.txt and creates new empty one
rm !!<Working Dir>!!/resources/BestDepth.txt
touch !!<Working Dir>!!/resources/BestDepth.txt

# runs python parser to get best Depth tester
python !!<Working Dir>!!/scripts/BestQueueDepth.py !!<Working Dir>!!/resources/DepthTest.txt !!<Working Dir>!!/resources/BestDepth.txt

# Add to history to see what its like from this point on I
!!<Working Dir>!!/resources/BestDepth.txt >> !!<Working Dir>!!/resources/history/bestHistory.txt

#Runs script with best.txt result as macro
.!!<Working Dir>!!/scripts/VIDIOBASH

# makes a new file for final results of big test
cp !!<Working Dir>!!/results/vidioResults.txt !!<Working Dir>!!/results/backupResults.txt
rm !!<Working Dir>!!/results/vidioResults.txt
touch !!<Working Dir>!!/results/vidioResults.txt
cp !!<Working Dir>!!/results/vidioMetaResults.txt !!<Working Dir>!!/results/backupMetaResults.txt
rm !!<Working Dir>!!/results/vidioMetaResults.txt
touch !!<Working Dir>!!/results/vidioMetaResults.txt

python !!<Working Dir>!!/scripts/vidioResultsParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioResults.txt
python !!<Working Dir>!!/scripts/vidioMeta Parser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioMetaResults.txt
cat !!<Working Dir>!!/results/vidioResults.txt
cat !!<Working Dir>!!/results/vidioMetaResults.txt

