#!/bin/bash
rm test.txt
cp vidioResults.txt backupResults.txt
rm vidioResults.txt
touch vidioResults.txt

best="$(cat best.txt)"


#-------------------------------------------------------------------------
#Single stream writes
echo "Starting single stream writes"
while read -r line
do
	echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/0/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/1/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/2/)

echo "Finished Single Stream writes"
#-------------------------------------------------------------------------
#Single stream reads

echo "Starting single stream reads"

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/0/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/1/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/2/)

echo "Finishing single stream reads"

#-------------------------------------------------------------------------
# Four stream writes

echo "Starting four stream writes"


while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)


echo "Finishing four stream writes"

#--------------------------------------------------------------------------
# Four stream reads

echo "Starting four stream reads"

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)

while read -r line
do
        echo "$line">>test.txt
done < <(/opt/vidio -D -f fa4k -q $best -n 2000 -r /mnt/rozofs01/vidio/3/ /mnt/rozofs01/vidio/4/ /mnt/rozofs01/vidio/5/ /mnt/rozofs01/vidio/6/)

echo "Finished four stream reads"

#------------------------------------------------------------------------
#Clean up and print results

