#!/bin/bash
# fileCreate measures the time it takes to create a 64kB file.
# Create is defined at: open file, write to file, close file.  
# Each indivdual file time is written to Avgtimes.txt in form: 
# Start time, finish time
# Overall time is printed at the end

# Deletes the old Values
sudo rm /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/resources/Avgtimes.txt
sudo touch /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/resources/Avgtimes.txt


sudo rm -rf /mnt/rozofs01/Meta/testfiles 
sudo mkdir -p /mnt/rozofs01/Meta/testfiles

# Records start of file Creation
total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

# Number of files 
for i in {1..100};
do

sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/resources/Avgtimes.txt

# Creates 1 file size 64000
dd < /dev/zero bs=64000 count=1 | sudo tee -a /mnt/rozofs01/Meta/testfiles/testfile$i


sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  /home/daniel/Documents/Programming/DTG-Benchmarking/Meta/resources/Avgtimes.txt


done

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

echo " "
echo " "
echo "total time: "

echo "$(($total2-$total1)) milliseconds"



