#!/bin/bash

cd /mnt/!!<Target Dir>!!/Meta/testfiles/

total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

find -maxdepth 1 -type d | while read -r dir; do printf "%s:\t" "$dir"; find "$dir" -type f | wc -l; done


# (sudo find /mnt/!!<Target Dir>!!/Meta/testfiles/ -type f | wc -l) > /dev/null

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

cd -
echo "It took $(($total2-$total1)) milliseconds to count !!<Number Files>!! files"

