#!/bin/bash
# fileCreate measures the time it takes to create a 64kB file.
# Create is defined at: open file, write to file, close file.  
# Each indivdual file time is written to Avgtimes.txt in form: 
# Start time, finish time
# Overall time is printed at the end

# Deletes the old Values
sudo rm !!<Working Dir>!!/resources/Avgtimes.txt
sudo touch !!<Working Dir>!!/resources/Avgtimes.txt

sudo chmod 777 !!<Working Dir>!!/resources/Avgtimes.txt
two=(2)
n=$((!!<Number Files>!! * $two))

half=$((!!<Number Files>!! / $two));
halfplus1=$(($half + 1))


echo $half
echo $halfplus1

echo $n | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt


sudo rm -rf /mnt/!!<Target Dir>!!/Meta/testfiles 
sudo mkdir -p /mnt/!!<Target Dir>!!/Meta/testfiles

# Records start of file Creation
total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

# Number of files 
for ((i=1; i<=$half; i++));
do

sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt

# Creates 1 file size !!<Size>!!
dd < /dev/zero bs=!!<Size>!! count=1 | sudo tee -a /mnt/!!<Target Dir>!!/Meta/testfiles/testfile$i


sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt


done


for ((i=$halfplus1; i<=!!<Number Files>!!; i++));
do

sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt

# Creates 1 file size !!<Size>!!
dd < /dev/zero bs=!!<Size>!! count=1 | sudo tee -a /mnt/!!<Target Dir>!!/Meta/testfiles/testfile$i


sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt


done


total2=$(($(date +'%s * 1000 + %-N')/ 1000000));
echo "total time: $(($total2-$total1)) milliseconds"
echo "total time: $(($total2-$total1)) milliseconds" | sudo tee -a !!<Working Dir>!!/resources/results.txt


sudo python !!<Working Dir>!!/scripts/avgResults.py !!<Working Dir>!!/resources/Avgtimes.txt | sudo tee -a !!<Working Dir>!!/resources/results.txt

