#!/bin/bash
# fileCreate measures the time it takes to create a 64kB file.
# Create is defined at: open file, write to file, close file.  
# Each indivdual file time is written to Avgtimes.txt in form: 
# Start time, finish time
# Overall time is printed at the end

# Deletes the old Values
sudo rm !!<Working Dir>!!/resources/Avgtimes.txt
sudo touch !!<Working Dir>!!/resources/Avgtimes.txt

sudo chmod 777 !!<Working Dir>!!/resources/Avgtimes.txt
two=(2)
n=$((!!<Number Files>!! * $two))

half=$((!!<Number Files>!! / $two));
halfplus1=$(($half + 1))


echo $half
echo $halfplus1

echo $n | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt


sudo rm -rf /mnt/!!<Target Dir>!!/Meta/testfiles 
sudo mkdir -p /mnt/!!<Target Dir>!!/Meta/testfiles/dir1/dir5
sudo mkdir -p /mnt/!!<Target Dir>!!/Meta/testfiles/dir2/dir6
sudo mkdir -p /mnt/!!<Target Dir>!!/Meta/testfiles/dir3/dir7
sudo mkdir -p /mnt/!!<Target Dir>!!/Meta/testfiles/dir4/dir8

# Records start of file Creation
total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

# Number of files 
for ((i=1; i<=$half; i=i+8));
do

sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir1/testfile$i !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir2/testfile$(($i+1)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir3/testfile$(($i+2)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir4/testfile$(($i+3)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir1/dir5/testfile$(($i+4)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir2/dir6/testfile$(($i+5)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir3/dir7/testfile$(($i+6)) !!<Size>!! &
sudo !!<Working Dir>!!/scripts/fileInit !!<Working Dir>!! /mnt/!!<Target Dir>!!/Meta/testfiles/dir4/dir8/testfile$(($i+7)) !!<Size>!! &



done


# for ((i=$halfplus1; i<=!!<Number Files>!!; i++));
# do

# sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt

# # Creates 1 file size !!<Size>!!
# dd < /dev/zero bs=!!<Size>!! count=1 | sudo tee -a /mnt/!!<Target Dir>!!/Meta/testfiles/testfile$i


# sudo echo $(($(date +'%s * 1000 + %-N')/ 1000000)) | sudo tee -a  !!<Working Dir>!!/resources/Avgtimes.txt


# done


total2=$(($(date +'%s * 1000 + %-N')/ 1000000));
echo "total time: $(($total2-$total1)) milliseconds"
echo "total time: $(($total2-$total1)) milliseconds" | sudo tee -a !!<Working Dir>!!/resources/results.txt


sudo python !!<Working Dir>!!/scripts/avgResults.py !!<Working Dir>!!/resources/Avgtimes.txt | sudo tee -a !!<Working Dir>!!/resources/results.txt

