#!/bin/bash

total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

sudo rm -rf /mnt/!!<Target Dir>!!/Meta/

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

echo "It took $(($total2-$total1)) milliseconds to remove !!<Number Files>!! files"

