#!/bin/bash
# Master shell script for vidio



for i in {0..15}; 
do 
	sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/; 
	#sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/;
	#sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/;
	#sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/;

done

#--------------------------------------------------------------------------------
# Sets up and executes DepthTesting

# Create DepthTest.txt
sudo rm !!<Working Dir>!!/resources/DepthTest.txt
sudo touch !!<Working Dir>!!/resources/DepthTest.txt

# Runs DepthTest
sudo !!<Working Dir>!!/scripts/VIDIODEPTHTESTER.sh

# Removes old best.txt and creates new empty one
sudo rm !!<Working Dir>!!/resources/BestDepth.txt
sudo touch !!<Working Dir>!!/resources/BestDepth.txt

# runs python parser to get best Depth tester
sudo python !!<Working Dir>!!/scripts/BestQueueDepth.py !!<Working Dir>!!/resources/DepthTest.txt !!<Working Dir>!!/resources/BestDepth.txt
#--------------------------------------------------------------------------------
# Sets up ad executes Frame Size Testing

# Creates SizeTest.txt
sudo rm !!<Working Dir>!!/resources/SizeTest.txt
sudo touch !!<Working Dir>!!/resources/SizeTest.txt

# Runs VIDIOFILESIZE
sudo !!<Working Dir>!!/scripts/VIDIOFILESIZE.sh

# Removes old BestSize.txt and creates new empty one
sudo rm !!<Working Dir>!!/resources/BestSize.txt
sudo touch !!<Working Dir>!!/resources/BestSize.txt

# Runs python parser to get best file size
sudo python !!<Working Dir>!!/scripts/BestFileSize.py !!<Working Dir>!!/resources/SizeTest.txt !!<Working Dir>!!/resources/BestSize.txt
#---------------------------------------------------------------------------------

# Add to history to see what its like from this point on I
echo !!<Working Dir>!!/resources/BestDepth.txt | sudo tee -a !!<Working Dir>!!/resources/history/bestHistory.txt

#Runs script with best.txt result as macro
sudo !!<Working Dir>!!/scripts/VIDIOBASH

# makes a new file for final results of big test
sudo cp !!<Working Dir>!!/results/vidioResults.txt !!<Working Dir>!!/results/backupResults.txt
sudo rm !!<Working Dir>!!/results/vidioResults.txt
sudo touch !!<Working Dir>!!/results/vidioResults.txt
sudo cp !!<Working Dir>!!/results/vidioMetaResults.txt !!<Working Dir>!!/results/backupMetaResults.txt
sudo rm !!<Working Dir>!!/results/vidioMetaResults.txt
sudo touch !!<Working Dir>!!/results/vidioMetaResults.txt

sudo python !!<Working Dir>!!/scripts/vidioResultsParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioResults.txt
sudo python !!<Working Dir>!!/scripts/vidioMetaParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioMetaResults.txt
sudo cat !!<Working Dir>!!/results/vidioResults.txt
sudo cat !!<Working Dir>!!/results/vidioMetaResults.txt

