#!/bin/bash
# Master shell script for vidio

# Removes any old file for Depthteseter script, then creates a new one


for i in {0..15}; do sudo mkdir -p /mnt/!!<Target Dir>!!/vidio/$i/; done

#------------------------------------------------------------------------------------------------------------------------------------------
# Depth Testing
sudo rm !!<Working Dir>!!/resources/DepthTest.txt
sudo touch !!<Working Dir>!!/resources/DepthTest.txt
# Runs the Depth tester script that outputs to test.txt
sudo !!<Working Dir>!!/scripts/VIDIODEPTHTESTER.sh

# Removes old best.txt and creates new empty one
sudo rm !!<Working Dir>!!/resources/BestDepth.txt
sudo touch !!<Working Dir>!!/resources/BestDepth.txt

# runs python parser to get best Depth tester
sudo python !!<Working Dir>!!/scripts/BestQueueDepth.py !!<Working Dir>!!/resources/DepthTest.txt !!<Working Dir>!!/resources/BestDepth.txt


#--------------------------------------------------------------------------------------------------------------------------------------------
# Size testing 
sudo rm !!<Working Dir>!!/resources/SizeTest.txt
sudo touch !!<Working Dir>!!/resources/SizeTest.txt

sudo !!<Working Dir>!!/scripts/VIDIOFILESIZE.sh

sudo rm !!<Working Dir>!!/resources/BestSize.txt
sudo touch !!<Working Dir>!!/resources/BestSize.txt

sudo python !!<Working Dir>!!/scripts/BestFileSize.py !!<Working Dir>!!/resources/SizeTest.txt !!<Working Dir>!!/resources/BestSize.txt
#-------------------------------------------------------------------------------------------------------------------------------------------

#Runs script with best.txt result as macro
sudo !!<Working Dir>!!/scripts/VIDIOBASH.sh

# makes a new file for final results of big test
sudo cp !!<Working Dir>!!/results/vidioResults.txt !!<Working Dir>!!/results/backupResults.txt
sudo rm !!<Working Dir>!!/results/vidioResults.txt
sudo touch !!<Working Dir>!!/results/vidioResults.txt
sudo cp !!<Working Dir>!!/results/vidioMetaResults.txt !!<Working Dir>!!/results/backupMetaResults.txt
sudo rm !!<Working Dir>!!/results/vidioMetaResults.txt
sudo touch !!<Working Dir>!!/results/vidioMetaResults.txt

sudo python !!<Working Dir>!!/scripts/vidioResultsParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioResults.txt
sudo python !!<Working Dir>!!/scripts/vidioMetaParser.py !!<Working Dir>!!/resources/test.txt !!<Working Dir>!!/results/vidioMetaResults.txt
sudo cat !!<Working Dir>!!/results/vidioResults.txt
sudo cat !!<Working Dir>!!/results/vidioMetaResults.txt

/mnt/!!<Target Dir>!!/vidio
