#!/bin/bash

total1=$(($(date +'%s * 1000 + %-N')/ 1000000));

(sudo ls /mnt/!!<Target Dir>!!/Meta/testfiles/) > /dev/null

total2=$(($(date +'%s * 1000 + %-N')/ 1000000));

echo "It took $(($total2-$total1)) milliseconds to list !!<Number Files>!! files"

