#!/bin/bash

# Deletes results and then recreates file w/ correct permissions
sudo rm !!<Working Dir>!!/resources/results.txt
sudo touch !!<Working Dir>!!/resources/results.txt
chmod 777 !!<Working Dir>!!/resources/results.txt


# Executes Meta testing
!!<Working Dir>!!/scripts/fileCreate 
!!<Working Dir>!!/scripts/fileList | sudo tee -a !!<Working Dir>!!/resources/results.txt
!!<Working Dir>!!/scripts/fileCount |  sudo tee -a !!<Working Dir>!!/resources/results.txt
!!<Working Dir>!!/scripts/fileSize |  sudo tee -a !!<Working Dir>!!/resources/results.txt
!!<Working Dir>!!/scripts/fileDelete |  sudo tee -a !!<Working Dir>!!/resources/results.txt

